export const MOSAIC_LIST_REQUEST = 'MOSAIC_LIST_REQUEST';
export const MOSAIC_LIST_SUCCESS = 'MOSAIC_LIST_SUCCESS';
export const MOSAIC_LIST_FAIL = 'MOSAIC_LIST_FAIL';

export const MOSAIC_DETAILS_REQUEST = 'MOSAIC_DETAILS_REQUEST';
export const MOSAIC_DETAILS_SUCCESS = 'MOSAIC_DETAILS_SUCCESS';
export const MOSAIC_DETAILS_FAIL = 'MOSAIC_DETAILS_FAIL';