export const MOSAIC_LIST_REQUEST = 'MOSAIC_LIST_REQUEST';
export const MOSAIC_LIST_SUCCESS = 'MOSAIC_LIST_SUCCESS';
export const MOSAIC_LIST_FAIL = 'MOSAIC_LIST_FAIL';

export const MOSAIC_DETAILS_REQUEST = 'MOSAIC_DETAILS_REQUEST';
export const MOSAIC_DETAILS_SUCCESS = 'MOSAIC_DETAILS_SUCCESS';
export const MOSAIC_DETAILS_FAIL = 'MOSAIC_DETAILS_FAIL';

export const MOSAIC_DELETE_REQUEST = 'MOSAIC_DELETE_REQUEST';
export const MOSAIC_DELETE_SUCCESS = 'MOSAIC_DELETE_SUCCESS';
export const MOSAIC_DELETE_FAIL = 'MOSAIC_DELETE_FAIL';

export const MOSAIC_CREATE_REQUEST = 'MOSAIC_CREATE_REQUEST';
export const MOSAIC_CREATE_SUCCESS = 'MOSAIC_CREATE_SUCCESS';
export const MOSAIC_CREATE_FAIL = 'MOSAIC_CREATE_FAIL';
export const MOSAIC_CREATE_RESET = 'MOSAIC_CREATE_RESET';

export const MOSAIC_UPDATE_REQUEST = 'MOSAIC_UPDATE_REQUEST';
export const MOSAIC_UPDATE_SUCCESS = 'MOSAIC_UPDATE_SUCCESS';
export const MOSAIC_UPDATE_FAIL = 'MOSAIC_UPDATE_FAIL';
export const MOSAIC_UPDATE_RESET = 'MOSAIC_UPDATE_RESET';

export const MOSAIC_CREATE_REVIEW_REQUEST = 'MOSAIC_CREATE_REVIEW_REQUEST';
export const MOSAIC_CREATE_REVIEW_SUCCESS = 'MOSAIC_CREATE_REVIEW_SUCCESS';
export const MOSAIC_CREATE_REVIEW_FAIL = 'MOSAIC_CREATE_REVIEW_FAIL';
export const MOSAIC_CREATE_REVIEW_RESET = 'MOSAIC_CREATE_REVIEW_RESET';